// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

"use client"; // 클라이언트 컴포넌트로 선언

import { useEffect, useState } from "react";

export default function RootLayout({ children }) {
  const [isAppRouter, setIsAppRouter] = useState(false); // 클라이언트 환경으로 변함에 따라 기본값을 true
  // Next.js 13+ 에서 app 폴더 내부의 컴포넌트는 기본적으로 서버 컴포넌트
  // useState, useEffect와 같은 클라이언트 사이드 기능을 사용하려면 클라이언트 컴포넌트로 명시적으로 선언
  // app/page.jsx와 pages/aa.jsx에서 동시에 사용할 수 있도록 나누어야함
  // pages/aa.jsx에서는 _app.js에서 RootLayout을 가지고 적용을 하기때문에 html이 2번 중독이 되서 html을 제거해야함
  // app/page.jsx에서는 html이 없기때문에 RootLayout이 html을 가지고 있어야함

  useEffect(() => {
    setIsAppRouter(true);
    // typeof window === "undefined"는 서버 환경에서만 true가 되고 클라이언트 환경에서는 false
  }, []);

  console.log(isAppRouter);

  if (isAppRouter) {
    // Next.js App Router (서버 렌더링)
    return (
      <html lang="ko">
        <body>
          <nav>공통 네비게이션</nav>
          <section>{children}</section>
          <footer>공통 푸터</footer>
        </body>
      </html>
    );
  } else {
    // Next.js Pages Router (클라이언트 렌더링)
    return (
      <>
        <header>Header3</header>
        <section>{children}</section>
        <footer>Footer3</footer>
      </>
    );
  }
}
